<?php
// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: 2026 Martien de Jong
// Source-Id: stm.misc.canary


declare(strict_types=1);

namespace WpPluginCheck;

/**
 * A generated, synthetic plugin that enqueues one oversized script on the front page.
 *
 * Plugin Check silently skips its runtime checks when they are not initialised
 * (the plugin is not active, or the runner was not started early). A clean
 * report from such a run would look exactly like a clean report from a full
 * run. The canary removes the doubt: it must trigger a known runtime finding
 * in the same sandbox, with the same command line, before the real plugin is
 * scanned. If it does not, the scan is reported as failed.
 */
final class Canary
{
    public const SLUG = 'pcp-runtime-canary';

    /** @return array<string,string> relative path => content */
    public static function files(): array
    {
        $main = <<<'PHP'
<?php
/**
 * Plugin Name: PCP Runtime Canary
 * Description: Synthetic plugin generated by the scanner to prove that runtime checks execute. Not a real plugin.
 * Version: 1.0.0
 * Requires at least: 6.0
 * Requires PHP: 7.4
 * License: GPL-2.0-or-later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: pcp-runtime-canary
 *
 * @package pcp-runtime-canary
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action(
	'wp_enqueue_scripts',
	static function () {
		wp_enqueue_script( 'pcp-runtime-canary-big', plugins_url( 'big.js', __FILE__ ), array(), '1.0.0', true );
	}
);
PHP;

        return [
            self::SLUG . '/pcp-runtime-canary.php' => $main . "\n",
            // 350,000 bytes of padding: above the 300,000 byte threshold of the script-size runtime check.
            self::SLUG . '/big.js'                 => str_repeat("/* pcp-canary synthetic padding */\n", 10000),
        ];
    }

    public static function install(string $pluginsDir): void
    {
        foreach (self::files() as $relative => $content) {
            $path = rtrim($pluginsDir, '/\\') . '/' . $relative;
            if (!is_dir(dirname($path))) {
                mkdir(dirname($path), 0777, true);
            }
            file_put_contents($path, $content);
        }
    }
}
